language: node_js
node_js: stable

install: true

branches:
  only:
  - master

before_script:
- git config --global user.name "wxyww2049"
- git config --global user.email "2049500915@qq.com"

script:

- git push -f https://$CI_TOKEN@github.com/wxyww2049/cdn.git HEAD:master
